"use client";

import React, { createContext, useContext, useState, useEffect, ReactNode } from "react";

export type Language = "en" | "si" | "ta";

interface LanguageContextType {
  language: Language;
  setLanguage: (lang: Language) => void;
  t: (key: string) => string;
}

const LanguageContext = createContext<LanguageContextType | undefined>(undefined);

const translations: Record<Language, Record<string, string>> = {
  en: {
    dashboard: "Citizen Dashboard",
    ai_insights: "AI Insights",
    alerts: "Active Alerts",
    sos: "SOS",
    safe_routes: "Safe Routes",
    situation_map: "Situation Map",
    updates: "Official Updates",
    quick_actions: "Quick Actions",
    report_incident: "Report Incident",
    finding_safe_route: "Finding Safe Route",
    network_status: "Network Status",
    live: "Live",
    offline_resources: "Offline Resources",
    download_briefing: "Download Briefing",
    hydro_analysis: "Hydro-Analysis",
    seismic_monitor: "Seismic Monitor",
    dispatch: "Dispatch",
    verify: "Verify",
    log_request: "Log Request",
    confidential: "CONFIDENTIAL",
    executive_summary: "EXECUTIVE SUMMARY",
    recommended_actions: "RECOMMENDED ACTIONS",
    back_to_dashboard: "Back to Dashboard",
    generate_report: "Generate Full Report",
    ai_dashboard_subtitle: "Real-time anomaly detection and predictive analysis for disaster management authorities using Deep Learning models.",
    total_reports: "Total Reports Processed",
    active_anomalies: "Active Anomalies",
    critical_sos: "Critical SOS Alerts",
    ai_confidence: "AI Confidence Score",
    water_levels_title: "Kelani River Water Levels",
    seismic_monitor_title: "Seismic Activity Monitor",
    nlp_analysis_title: "AI Message Summary (NLP Analysis)",
    priority_sos_feed: "Priority SOS Feed",
    emergency_level: "EMERGENCY LEVEL",
    online: "Online",
    emergency_hotlines: "Emergency Hotlines",
    dmc_rights: "Disaster Management Center of Sri Lanka. All rights reserved.",
    all: "All",
    critical: "Critical",
    high: "High",
    requires_attention: "Requires immediate attention",
    stable: "Stable",
    intelligence_briefing: "Intelligence Briefing",
    print_pdf: "Print PDF",
    copy_clipboard: "Copy to Clipboard",
    restricted: "Restricted",
    generated_by: "Generated By",
    immediate_threats: "Immediate Threats",
    affected_infrastructure: "Affected Infrastructure",
    prediction_report: "Detailed AI Prediction Report",
    share_dmc: "Share with DMC",
    download_pdf: "Download PDF",
    flood_threshold: "Flood Threshold",
    risk_level: "Risk Level",
    affected_population: "Affected Population (Est.)",
    response_status: "Response Status",
    seismic_clusters: "Seismic Clusters",
    critical_hotspots: "Identified Critical Hotspots",
    normal_activity: "Normal Activity",
    high_activity: "High Activity"
  },
  si: {
    dashboard: "පුරවැසි උපකරණ පුවරුව",
    ai_insights: "කෘතිම බුද්ධි තොරතුරු",
    alerts: "සක්‍රීය අනතුරු ඇඟවීම්",
    sos: "හදිසි සහය",
    safe_routes: "ආරක්ෂිත මාර්ග",
    situation_map: "තත්ව සිතියම",
    updates: "නිල යාවත්කාලීන කිරීම්",
    quick_actions: "කඩිනම් ක්‍රියාමාර්ග",
    report_incident: "සිදුවීමක් වාර්තා කරන්න",
    finding_safe_route: "ආරක්ෂිත මාර්ගය සෙවීම",
    network_status: "ජාල තත්ත්වය",
    live: "සජීවී",
    offline_resources: "නොබැඳි සම්පත්",
    download_briefing: "සාරාංශය බාගත කරන්න",
    hydro_analysis: "ජල විද්‍යාත්මක විශ්ලේෂණය",
    seismic_monitor: "භූ කම්පන නිරීක්ෂණය",
    dispatch: "යැවීම",
    verify: "තහවුරු කරන්න",
    log_request: "සටහන් කරන්න",
    confidential: "රහස්‍ය",
    executive_summary: "විධායක සාරාංශය",
    recommended_actions: "නිර්දේශිත ක්‍රියාමාර්ග",
    back_to_dashboard: "නැවත පුවරුවට",
    generate_report: "සම්පූර්ණ වාර්තාව",
    ai_dashboard_subtitle: "Deep Learning ආකෘති භාවිතා කරමින් පවතින තත්වයන් හඳුනා ගැනීම සහ අනාවැකි විශ්ලේෂණය කිරීම.",
    total_reports: "සැකසූ මුළු වාර්තා",
    active_anomalies: "සක්‍රීය විෂමතා",
    critical_sos: "බරපතල SOS නිවේදන",
    ai_confidence: "AI විශ්වාසනීය මට්ටම",
    water_levels_title: "කැලණි ගඟේ ජල මට්ටම්",
    seismic_monitor_title: "භූ කම්පන නිරීක්ෂණය",
    nlp_analysis_title: "AI පණිවිඩ සාරාංශය (NLP විශ්ලේෂණය)",
    priority_sos_feed: "ප්‍රමුඛතා SOS පෝෂණය",
    emergency_level: "හදිසි මට්ටම",
    online: "සක්‍රීයයි",
    emergency_hotlines: "හදිසි දුරකථන අංක",
    dmc_rights: "ශ්‍රී ලංකා ආපදා කළමනාකරණ මධ්‍යස්ථානය. සියලුම හිමිකම් ඇවිරිණි.",
    all: "සියල්ල",
    critical: "බරපතල",
    high: "ඉහළ",
    requires_attention: "වහාම අවධානය යොමු කළ යුතුය",
    stable: "ස්ථාවරයි",
    intelligence_briefing: "බුද්ධි තොරතුරු සාරාංශය",
    print_pdf: "PDF මුද්‍රණය කරන්න",
    copy_clipboard: "පිටපත් කරන්න",
    restricted: "සීමිතයි",
    generated_by: "නිර්මාණය කළේ",
    immediate_threats: "ක්ෂණික තර්ජන",
    affected_infrastructure: "බලපෑමට ලක් වූ යටිතල පහසුකම්",
    prediction_report: "සවිස්තරාත්මක AI අනාවැකි වාර්තාව",
    share_dmc: "DMC සමඟ බෙදාගන්න",
    download_pdf: "PDF බාගන්න",
    flood_threshold: "ගංවතුර සීමාව",
    risk_level: "අවදානම් මට්ටම",
    affected_population: "බලපෑමට ලක් වූ ජනගහනය (අනුමාන)",
    response_status: "ප්‍රතිචාර තත්ත්වය",
    seismic_clusters: "භූ කම්පන පොකුරු",
    critical_hotspots: "හඳුනාගත් අවදානම් මධ්‍යස්ථාන",
    normal_activity: "සාමාන්්‍ය තත්ත්වය",
    high_activity: "ඉහළ ක්‍රියාකාරීත්වය"
  },
  ta: {
    dashboard: "குடிமக்கள் டாஷ்போர்டு",
    ai_insights: "AI நுண்ணறிவு",
    alerts: "செயலில் உள்ள எச்சரிக்கைகள்",
    sos: "அவசரகால உதவி",
    safe_routes: "பாதுகாப்பான பாதைகள்",
    situation_map: "நிலைமை வரைபடம்",
    updates: "அதிகாரப்பூர்வ அறிவிப்புகள்",
    quick_actions: "விரைவான நடவடிக்கைகள்",
    report_incident: "சம்பவத்தைப் புகாரளிக்கவும்",
    finding_safe_route: "பாதுகாப்பான பாதையைக் கண்டறிதல்",
    network_status: "பிணைய நிலை",
    live: "நேரடி",
    offline_resources: "ஆஃப்லைன் ஆதாரங்கள்",
    download_briefing: "சுருக்கத்தைப் பதிவிறக்கவும்",
    hydro_analysis: "நீரியல் பகுப்பாய்வு",
    seismic_monitor: "நில அதிர்வு கண்காணிப்பு",
    dispatch: "அனுப்பு",
    verify: "சரிபார்",
    log_request: "பதிவு செய்க",
    confidential: "ரகசியமானது",
    executive_summary: "நிர்வாகச் சுருக்கம்",
    recommended_actions: "பரிந்துரைக்கப்பட்ட நடவடிக்கைகள்",
    back_to_dashboard: "டாஷ்போர்டுக்குத் திரும்பு",
    generate_report: "முழு அறிக்கையை உருவாக்கு",
    ai_dashboard_subtitle: "ஆழ்ந்த கற்றல் மாதிரிகளைப் பயன்படுத்தி நிகழ்நேர முரண்பாடு கண்டறிதல் மற்றும் முன்கணிப்பு பகுப்பாய்வு.",
    total_reports: "மொத்த அறிக்கைகள்",
    active_anomalies: "செயலில் உள்ள முரண்பாடுகள்",
    critical_sos: "முக்கியமான SOS எச்சரிக்கைகள்",
    ai_confidence: "AI நம்பிக்கை மதிப்பெண்",
    water_levels_title: "களனி கங்கை நீர் நிலைகள்",
    seismic_monitor_title: "நில அதிர்வு கண்காணிப்பு",
    nlp_analysis_title: "AI செய்தி சுருக்கம் (NLP பகுப்பாய்வு)",
    priority_sos_feed: "முன்னுரிமை SOS ஊட்டம்",
    emergency_level: "அவசரநிலை அளவு",
    online: "செயல்பாட்டில்",
    emergency_hotlines: "அவசர தொலைபேசி எண்கள்",
    dmc_rights: "இலங்கை பேரிடர் மேலாண்மை மையம். அனைத்து உரிமைகளும் பாதுகாக்கப்பட்டவை.",
    all: "எல்லாம்",
    critical: "முக்கியமான",
    high: "உயர்",
    requires_attention: "உடனடி கவனம் தேவை",
    stable: "நிலையானது",
    intelligence_briefing: "புலனாய்வு சுருக்கம்",
    print_pdf: "PDF அச்சிடுக",
    copy_clipboard: "நகலெடுக்க",
    restricted: "கட்டுப்படுத்தப்பட்டது",
    generated_by: "உருவாக்கியவர்",
    immediate_threats: "உடனடி அச்சுறுத்தல்கள்",
    affected_infrastructure: "பாதிக்கப்பட்ட உள்கட்டமைப்பு",
    prediction_report: "விரிவான AI முன்கணிப்பு அறிக்கை",
    share_dmc: "DMC உடன் பகிரவும்",
    download_pdf: "PDF பதிவிறக்கவும்",
    flood_threshold: "வெள்ள வரம்பு",
    risk_level: "ஆபத்து நிலை",
    affected_population: "பாதிக்கப்பட்ட மக்கள் தொகை (மதிப்பீடு)",
    response_status: "பதில் நிலை",
    seismic_clusters: "பூகம்பக் கூட்டங்கள்",
    critical_hotspots: "அடையாளம் காணப்பட்ட முக்கிய இடங்கள்",
    normal_activity: "சாதாரண செயல்பாடு",
    high_activity: "அதிக செயல்பாடு"
  }
};

export function LanguageProvider({ children }: { children: ReactNode }) {
  const [language, setLanguage] = useState<Language>("en");

  // Load language from localStorage if available
  useEffect(() => {
    const savedLang = localStorage.getItem("outbreak_lang") as Language;
    if (savedLang && (savedLang === "en" || savedLang === "si" || savedLang === "ta")) {
      setLanguage(savedLang);
    }
  }, []);

  const handleSetLanguage = (lang: Language) => {
    setLanguage(lang);
    localStorage.setItem("outbreak_lang", lang);
  };

  const t = (key: string) => {
    return translations[language][key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage: handleSetLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
}

export function useLanguage() {
  const context = useContext(LanguageContext);
  if (context === undefined) {
    throw new Error("useLanguage must be used within a LanguageProvider");
  }
  return context;
}
